### ISSUE TITLE
CTFL Vertragsmanager + Kotlin App

### ISSUE THREAD

**Issue by christian-leingang** [michael-spengler/wwi19seb-native-entwicklung-mobiler-applikationen#4]
Weiterentwicklung am Flutter Projekt "CTFL" des 5. Semesters: https://github.com/christian-leingang/CTFL-Vertragsmanager

Erkundung der Kotlin Welt mit einer Kotlin-App, welche sich an Levana's Bachelorarbeits-Prototypen orientiert: https://github.com/christian-leingang/KotlinKameraTest

**Comment by michael-spengler** [comment]
Präsentation Top
CICD, Frontend, Backend, Provisioning ... --> Volles Programm
Lizenzfrage klären
